import type { Profile, Job, JobWithAssignee, Invoice, InvoiceWithJob, Customer, CustomerWithStats } from '@/lib/supabase/types'

export const isDemoMode = !process.env.NEXT_PUBLIC_SUPABASE_URL

export const demoProfile: Profile = {
  id: 'demo-owner-id',
  email: 'vin@moderntile.pro',
  full_name: 'Vincenzo',
  role: 'owner',
  phone: '(617) 766-1259',
  is_active: true,
  created_at: '2025-01-01T00:00:00Z',
  last_location_lat: 42.4084,
  last_location_lng: -71.0120,
  last_location_updated_at: '2026-04-03T09:30:00Z',
}

const demoLead: Profile = {
  id: 'demo-lead-id',
  email: 'carlos@moderntile.pro',
  full_name: 'Carlos Rivera',
  role: 'lead',
  phone: '(617) 555-0199',
  is_active: true,
  created_at: '2025-01-15T00:00:00Z',
  last_location_lat: 42.3601,
  last_location_lng: -71.0589,
  last_location_updated_at: '2026-04-03T08:45:00Z',
}

export const demoTeamMembers: Profile[] = [demoProfile, demoLead]

// Real customers from Notion Tile Jobs Dashboard
export const demoCustomers: Customer[] = [
  {
    id: 'cust-infante',
    name: 'Pamela Infante',
    email: null,
    phone: '(214) 983-6715',
    address: null,
    city: null,
    state: null,
    zip: null,
    notes: 'Multi-part bathroom project. Plumber Scott from All Things Plumbing Co coordinating.',
    source: 'manual',
    stripe_customer_id: null,
    notion_page_id: '32e35a99-cefd-8182-98d1-d08d0c648ff4',
    created_at: '2026-03-25T10:00:00Z',
    updated_at: '2026-03-31T18:26:00Z',
  },
  {
    id: 'cust-wickersty',
    name: 'Jeffrey Wickersty',
    email: 'jeff@wickersty.com',
    phone: '551-655-0653',
    address: '35 Fremont Street',
    city: 'Winthrop',
    state: 'MA',
    zip: null,
    notes: 'Repeat customer. Pipe burst caused water damage.',
    source: 'repeat',
    stripe_customer_id: null,
    notion_page_id: '32935a99-cefd-8170-8738-f5fb576055b4',
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-03-31T18:43:00Z',
  },
  {
    id: 'cust-benoit',
    name: 'Adam Benoit',
    email: 'adam.l.benoit@gmail.com',
    phone: '7745266236',
    address: '366 Wickenden Street',
    city: 'Providence',
    state: 'RI',
    zip: null,
    notes: 'Two projects: 143 Sheldon + Wickenden. New construction.',
    source: 'referral',
    stripe_customer_id: null,
    notion_page_id: null,
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-03-22T13:36:00Z',
  },
  {
    id: 'cust-maniscalco',
    name: 'Stephanie Maniscalco',
    email: null,
    phone: null,
    address: '6 Mallard Lane',
    city: 'East Bridgewater',
    state: 'MA',
    zip: '02333',
    notes: 'Wayne said project will most likely start before end of April.',
    source: 'manual',
    stripe_customer_id: null,
    notion_page_id: '33635a99-cefd-81b9-8d93-da1f2e4fbef9',
    created_at: '2026-03-28T10:00:00Z',
    updated_at: '2026-04-02T17:00:00Z',
  },
  {
    id: 'cust-brooks',
    name: 'Nancy Brooks',
    email: 'nlbrooksnancy@netscape.net',
    phone: '617-922-5117',
    address: '260 Tremont St, Unit 3',
    city: 'Melrose',
    state: 'MA',
    zip: null,
    notes: 'Parking: Space 19 behind building. Text 10 mins out.',
    source: 'website',
    stripe_customer_id: null,
    notion_page_id: '2ef35a99-cefd-81da-8d19-de166ca43222',
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-30T17:00:00Z',
  },
  {
    id: 'cust-qargo',
    name: 'Qargo Coffee',
    email: null,
    phone: null,
    address: '99 Blackstone St',
    city: 'Boston',
    state: 'MA',
    zip: '02109',
    notes: 'Commercial cafe buildout. Multi-trade scope.',
    source: 'manual',
    stripe_customer_id: null,
    notion_page_id: '31135a99-cefd-81ba-9b65-ec2dbf22b043',
    created_at: '2026-02-20T10:00:00Z',
    updated_at: '2026-04-02T17:14:00Z',
  },
  {
    id: 'cust-aaron-gc',
    name: 'Aaron (GC)',
    email: null,
    phone: null,
    address: null,
    city: 'North Shore',
    state: 'MA',
    zip: null,
    notes: 'General contractor. Multiple projects.',
    source: 'referral',
    stripe_customer_id: null,
    notion_page_id: null,
    created_at: '2026-02-15T10:00:00Z',
    updated_at: '2026-03-31T17:52:00Z',
  },
  {
    id: 'cust-somerville-repair',
    name: 'Somerville Floor Repair',
    email: null,
    phone: '(617) 780-0995',
    address: '7 Dickinson St',
    city: 'Somerville',
    state: 'MA',
    zip: '02143',
    notes: 'DIY epoxy fix failed. Loose tiles clicking.',
    source: 'manual',
    stripe_customer_id: null,
    notion_page_id: '33435a99-cefd-81e1-9bd1-e446e0ea1357',
    created_at: '2026-03-31T10:00:00Z',
    updated_at: '2026-03-31T17:41:00Z',
  },
]

export function getDemoCustomer(id: string): Customer | undefined {
  return demoCustomers.find((c) => c.id === id)
}

// Geocoded coordinates for real job addresses
export const demoJobCoordinates: Record<string, [number, number]> = {
  'job-infante': [42.4084, -71.0120],         // Local area
  'job-wickersty': [42.3756, -70.9828],        // Winthrop
  'job-adler-box': [42.5370, -70.8969],        // North Shore
  'job-wickenden': [41.8205, -71.4023],        // Providence RI
  'job-maniscalco': [42.0334, -70.9401],       // East Bridgewater
  'job-brooks': [42.4551, -71.0589],           // Melrose
  'job-qargo': [42.3609, -71.0545],            // Boston (Blackstone St)
  'job-aaron-floor': [42.4800, -70.9500],      // North Shore
  'job-somerville-repair': [42.3801, -71.0989], // Somerville
}

// Real jobs from Notion Tile Jobs Dashboard
export const demoJobs: JobWithAssignee[] = [
  {
    id: 'job-infante',
    job_number: 1,
    title: 'Infante - Bathroom Tile + Ceiling',
    status: 'scheduled',
    customer_id: 'cust-infante',
    client_name: 'Pamela Infante',
    client_phone: '(214) 983-6715',
    client_email: null,
    client_address: null,
    job_type: 'Bathroom Tile',
    square_footage: null,
    scope_notes: 'Multi-part bathroom project. Pt 1: ceiling tile (has materials). Pt 2: bathroom tile after demo. Plumber Scott from All Things Plumbing Co coordinating on plumbing work. Radiator connection height issue needs fixing during retile.',
    scheduled_start: '2026-04-03',
    scheduled_end: null,
    estimated_days: null,
    actual_days: null,
    estimated_cost: null,
    actual_cost: null,
    amount_invoiced: 0,
    amount_paid: 0,
    line_items: [],
    stripe_customer_id: null,
    notion_page_id: '32e35a99-cefd-8182-98d1-d08d0c648ff4',
    notion_last_synced_at: '2026-04-03T14:00:00Z',
    assigned_to: 'demo-owner-id',
    notes: 'ACTION ITEMS:\n- Pick up piece of stone from Spencer\'s Plumbing in Peabody\n- Collect deposit from Pamela before job starts\n\nCustomer providing tile. Demo starts April 3rd after 3pm, tile work continues April 4th.',
    created_by: 'demo-owner-id',
    created_at: '2026-03-25T10:00:00Z',
    updated_at: '2026-03-31T18:26:00Z',
    assignee: demoProfile,
  },
  {
    id: 'job-wickersty',
    job_number: 2,
    title: 'Wickersty - Winthrop Water Damage Repair + Tile Install',
    status: 'in_progress',
    customer_id: 'cust-wickersty',
    client_name: 'Jeffrey Wickersty',
    client_phone: '551-655-0653',
    client_email: 'jeff@wickersty.com',
    client_address: '35 Fremont Street, Winthrop, MA',
    job_type: 'Tile Repair',
    square_footage: 280,
    scope_notes: 'Pipe burst caused water damage. TWO INVOICES: (1) Demo & debris removal — $400. (2) Tile install — 280 sq ft @ $12.50/sq ft = $3,500.\n\nMaterials: We provide Strata Mat, various thinsets, labor. Client provides tile, grout, transition pieces.',
    scheduled_start: '2026-03-25',
    scheduled_end: null,
    estimated_days: 2,
    actual_days: null,
    estimated_cost: 3900,
    actual_cost: 1609,
    amount_invoiced: 3900,
    amount_paid: 0,
    line_items: [
      { category: 'labor', description: 'Demo & debris removal', quantity: 1, unit: 'ea', unit_price: 400, amount: 400 },
      { category: 'materials', description: 'Strata Mat underlayment', quantity: 280, unit: 'sq ft', unit_price: 1.50, amount: 420 },
      { category: 'materials', description: 'Thinset 254 Platinum', quantity: 4, unit: 'bag', unit_price: 45, amount: 180 },
      { category: 'labor', description: 'Tile installation (280 sq ft)', quantity: 280, unit: 'sq ft', unit_price: 8.93, amount: 2500 },
      { category: 'labor', description: 'Trash disposal', quantity: 1, unit: 'ea', unit_price: 150, amount: 150 },
    ],
    stripe_customer_id: null,
    notion_page_id: '32935a99-cefd-8170-8738-f5fb576055b4',
    notion_last_synced_at: '2026-04-03T14:00:00Z',
    assigned_to: 'demo-lead-id',
    notes: 'Repeat customer. Strata Mat underlayment — use 254 Platinum thinset (not 253 Gold). Payment on install: 10% deposit ($350) to schedule, remaining $3,150 at completion.',
    created_by: 'demo-owner-id',
    created_at: '2026-03-20T10:00:00Z',
    updated_at: '2026-03-31T18:43:00Z',
    assignee: demoLead,
  },
  {
    id: 'job-adler-box',
    job_number: 3,
    title: 'Adler Box - 143 Sheldon Residential Tile',
    status: 'quoted',
    customer_id: 'cust-benoit',
    client_name: 'Adam Benoit',
    client_phone: null,
    client_email: null,
    client_address: '143 Sheldon Adler',
    job_type: 'Bathroom Tile',
    square_footage: null,
    scope_notes: 'Bathroom 1: Curbless shower w/ KERDI-LINE linear drain, 48" half wall, full KERDI-BOARD substrate, 18" recessed niche, DITRA-HEAT floor heating (~50-60 sq ft). Entryway: ~36 sq ft floor tile.\n\nConfirmed: $9,800. Full project mid-range: ~$13,000-$16,000.',
    scheduled_start: null,
    scheduled_end: null,
    estimated_days: 5,
    actual_days: null,
    estimated_cost: 9800,
    actual_cost: null,
    amount_invoiced: 0,
    amount_paid: 0,
    line_items: [
      { category: 'materials', description: 'Schluter KERDI waterproofing system', quantity: 1, unit: 'ea', unit_price: 2400, amount: 2400 },
      { category: 'materials', description: 'DITRA-HEAT membrane + cable + thermostat', quantity: 55, unit: 'sq ft', unit_price: 12.60, amount: 693 },
      { category: 'materials', description: 'Thinset, grout, sealant, backer board', quantity: 1, unit: 'ea', unit_price: 500, amount: 500 },
      { category: 'labor', description: 'Bathroom 1 complete tile package', quantity: 5, unit: 'hr', unit_price: 950, amount: 4750 },
      { category: 'labor', description: 'Entryway floor tile (~36 sq ft)', quantity: 4, unit: 'hr', unit_price: 85, amount: 340 },
    ],
    stripe_customer_id: null,
    notion_page_id: '31135a99-cefd-81d8-bf3c-e703a57a1d6c',
    notion_last_synced_at: '2026-04-03T14:00:00Z',
    assigned_to: null,
    notes: 'Pending areas: Studio/garage wet room ($1,200-$4,000), hearth tile ($800-$1,200), quartz pieces ($300-$500).',
    created_by: 'demo-owner-id',
    created_at: '2026-02-23T10:00:00Z',
    updated_at: '2026-03-22T13:36:00Z',
    assignee: null,
  },
  {
    id: 'job-wickenden',
    job_number: 4,
    title: 'Wickenden - 2 Bathrooms + Kitchen Backsplash',
    status: 'quoted',
    customer_id: 'cust-benoit',
    client_name: 'Adam Benoit',
    client_phone: '7745266236',
    client_email: 'adam.l.benoit@gmail.com',
    client_address: '366 Wickenden Street, Providence, RI',
    job_type: 'Bathroom Tile',
    square_footage: 238,
    scope_notes: 'Option A (Full Service): $11,500 — Turnkey waterproofing + tile, 7 days. Option B (Tile Only): $6,500 — 5 days.\n\nBath 1: ~70 sq ft wall + ~40 sq ft floor mosaic. Bath 2: ~58 sq ft wall + ~20 sq ft floor, linear drain, floor warming. Kitchen: ~50 sq ft subway backsplash.',
    scheduled_start: null,
    scheduled_end: null,
    estimated_days: 7,
    actual_days: null,
    estimated_cost: 11500,
    actual_cost: null,
    amount_invoiced: 0,
    amount_paid: 0,
    line_items: [
      { category: 'materials', description: 'Waterproofing & shower build system', quantity: 1, unit: 'ea', unit_price: 2411, amount: 2411 },
      { category: 'materials', description: 'Floor warming system (Bath 2)', quantity: 1, unit: 'ea', unit_price: 693, amount: 693 },
      { category: 'materials', description: 'Setting & finishing materials', quantity: 1, unit: 'ea', unit_price: 868, amount: 868 },
      { category: 'labor', description: 'Tile installation (2-person crew, 7 days)', quantity: 7, unit: 'hr', unit_price: 1000, amount: 7000 },
      { category: 'labor', description: 'Transportation (Revere → Providence)', quantity: 1, unit: 'ea', unit_price: 549, amount: 549 },
    ],
    stripe_customer_id: null,
    notion_page_id: '31135a99-cefd-8152-9087-e095a1d33a72',
    notion_last_synced_at: '2026-04-03T14:00:00Z',
    assigned_to: 'demo-owner-id',
    notes: 'Estimate #WK-2026-001 | Valid through March 23, 2026. New construction - no demo needed. Electrician required for thermostat connection.',
    created_by: 'demo-owner-id',
    created_at: '2026-02-21T10:00:00Z',
    updated_at: '2026-03-22T13:36:00Z',
    assignee: demoProfile,
  },
  {
    id: 'job-maniscalco',
    job_number: 5,
    title: 'Maniscalco - East Bridgewater Floor Tile Install',
    status: 'quoted',
    customer_id: 'cust-maniscalco',
    client_name: 'Stephanie Maniscalco',
    client_phone: null,
    client_email: null,
    client_address: '6 Mallard Lane, East Bridgewater, MA 02333',
    job_type: 'Floor Tile',
    square_footage: 500,
    scope_notes: 'Floor tile installation — 500 sq ft @ $12.50/sq ft = $6,250. Includes Strata Mat, various thinsets, and labor.\n\nMaterials: We provide Strata Mat, thinsets, labor. Customer provides tile, grout, transition pieces.',
    scheduled_start: null,
    scheduled_end: null,
    estimated_days: null,
    actual_days: null,
    estimated_cost: 6250,
    actual_cost: null,
    amount_invoiced: 0,
    amount_paid: 0,
    line_items: [
      { category: 'materials', description: 'Strata Mat underlayment', quantity: 500, unit: 'sq ft', unit_price: 1.50, amount: 750 },
      { category: 'materials', description: 'Various thinsets', quantity: 8, unit: 'bag', unit_price: 45, amount: 360 },
      { category: 'labor', description: 'Floor tile installation', quantity: 500, unit: 'sq ft', unit_price: 10.28, amount: 5140 },
    ],
    stripe_customer_id: null,
    notion_page_id: '33635a99-cefd-81b9-8d93-da1f2e4fbef9',
    notion_last_synced_at: '2026-04-03T14:00:00Z',
    assigned_to: null,
    notes: 'PAYMENT SCHEDULE: 10% deposit ($625) to schedule, 30% ($1,875) after first day, remaining balance ($3,750) at completion. Wayne said project will most likely start before end of April.',
    created_by: 'demo-owner-id',
    created_at: '2026-04-02T10:00:00Z',
    updated_at: '2026-04-02T17:00:00Z',
    assignee: null,
  },
  {
    id: 'job-brooks',
    job_number: 6,
    title: 'Brooks - Melrose Floor Tile',
    status: 'paid',
    customer_id: 'cust-brooks',
    client_name: 'Nancy Brooks',
    client_phone: '617-922-5117',
    client_email: 'nlbrooksnancy@netscape.net',
    client_address: '260 Tremont St, Melrose, Unit 3',
    job_type: 'Floor Tile',
    square_footage: 55,
    scope_notes: 'Install Strata Mat underlayment and hexagon tile on bathroom floor and entryway over concrete slab. Includes sealer application.\n\nMaterials: We provide Strata Mat, Thinset 254 Platinum, Caulking, Impregnator Sealer. Client provides hexagon mesh tile, grout.',
    scheduled_start: '2026-01-29',
    scheduled_end: '2026-01-30',
    estimated_days: 1.5,
    actual_days: 2,
    estimated_cost: 1623,
    actual_cost: 997,
    amount_invoiced: 1623,
    amount_paid: 1623,
    line_items: [
      { category: 'materials', description: 'Strata Mat (prorated)', quantity: 55, unit: 'sq ft', unit_price: 1.50, amount: 82.50 },
      { category: 'materials', description: 'Thinset 254 Platinum', quantity: 2, unit: 'bag', unit_price: 45, amount: 90 },
      { category: 'materials', description: 'Caulking + Impregnator Sealer', quantity: 1, unit: 'ea', unit_price: 65, amount: 65 },
      { category: 'labor', description: 'Hexagon tile installation + sealer', quantity: 12, unit: 'hr', unit_price: 95, amount: 1140 },
      { category: 'labor', description: 'Strata Mat prep', quantity: 3, unit: 'hr', unit_price: 85, amount: 255 },
    ],
    stripe_customer_id: null,
    notion_page_id: '2ef35a99-cefd-81da-8d19-de166ca43222',
    notion_last_synced_at: '2026-04-03T14:00:00Z',
    assigned_to: 'demo-lead-id',
    notes: 'PARKING: Space 19 behind building (# may be covered by snow). Also visitor parking on side of building in front of dumpster. Text Nancy 10 mins out.',
    created_by: 'demo-owner-id',
    created_at: '2026-01-21T10:00:00Z',
    updated_at: '2026-01-30T17:00:00Z',
    assignee: demoLead,
  },
  {
    id: 'job-aaron-floor',
    job_number: 7,
    title: 'Aaron (GC) - North Shore Bathroom Floor w/ Ditra-Heat',
    status: 'quoted',
    customer_id: 'cust-aaron-gc',
    client_name: 'Aaron',
    client_phone: null,
    client_email: null,
    client_address: 'North Shore (~15 miles from Revere)',
    job_type: 'Floor Tile',
    square_footage: 130,
    scope_notes: 'Existing floor is tile over Ditra-Heat — demo includes removing old tile + old membrane/cable system. ~780 lbs of tile debris. Trash disposal $500.\n\nMaterials: We provide Ditra-Heat peel & stick membrane (16 sheets), cable (134.3 sq ft), RS1 Smart Thermostat, ALL-SET (6 bags), grout, caulking. Aaron supplies tile (~143 sq ft).',
    scheduled_start: null,
    scheduled_end: null,
    estimated_days: 3.5,
    actual_days: null,
    estimated_cost: 6668,
    actual_cost: 3910,
    amount_invoiced: 0,
    amount_paid: 0,
    line_items: [
      { category: 'materials', description: 'Ditra-Heat peel & stick membrane (16 sheets)', quantity: 16, unit: 'ea', unit_price: 30, amount: 480 },
      { category: 'materials', description: 'Ditra-Heat 120V cable (134.3 sq ft)', quantity: 1, unit: 'ea', unit_price: 900, amount: 900 },
      { category: 'materials', description: 'Ditra-Heat RS1 Smart Thermostat', quantity: 1, unit: 'ea', unit_price: 250, amount: 250 },
      { category: 'materials', description: 'Schluter ALL-SET thinset (6 bags)', quantity: 6, unit: 'bag', unit_price: 45, amount: 270 },
      { category: 'labor', description: 'Demo (old tile + Ditra system)', quantity: 8, unit: 'hr', unit_price: 85, amount: 680 },
      { category: 'labor', description: 'Ditra-Heat + tile installation', quantity: 20, unit: 'hr', unit_price: 95, amount: 1900 },
      { category: 'labor', description: 'Trash disposal (~780 lbs)', quantity: 1, unit: 'ea', unit_price: 500, amount: 500 },
    ],
    stripe_customer_id: null,
    notion_page_id: '31935a99-cefd-8190-8086-f34ea020a8db',
    notion_last_synced_at: '2026-04-03T14:00:00Z',
    assigned_to: null,
    notes: 'Aaron is GC. Confirm existing electrical is 120V compatible. Labor priced at $1,000/day to customer. ALL-SET thinset required for Schluter system (not 253 Gold).',
    created_by: 'demo-owner-id',
    created_at: '2026-03-04T10:00:00Z',
    updated_at: '2026-03-31T17:52:00Z',
    assignee: null,
  },
  {
    id: 'job-somerville-repair',
    job_number: 8,
    title: 'Somerville Floor Repair - 7 Dickinson St',
    status: 'lead',
    customer_id: 'cust-somerville-repair',
    client_name: '(617) 780-0995',
    client_phone: '(617) 780-0995',
    client_email: null,
    client_address: '7 Dickinson St, Somerville MA 02143',
    job_type: 'Tile Repair',
    square_footage: null,
    scope_notes: 'Loose floor tiles — customer attempted DIY epoxy fix but still clicking and floor doesn\'t feel solid. Considering asking original contractor for refund.',
    scheduled_start: null,
    scheduled_end: null,
    estimated_days: null,
    actual_days: null,
    estimated_cost: null,
    actual_cost: null,
    amount_invoiced: 0,
    amount_paid: 0,
    line_items: [],
    stripe_customer_id: null,
    notion_page_id: '33435a99-cefd-81e1-9bd1-e446e0ea1357',
    notion_last_synced_at: '2026-04-03T14:00:00Z',
    assigned_to: null,
    notes: 'Customer called about loose floor tiles. Previously discussed tiling job a couple months ago. Vin mentioned MA customer satisfaction laws may provide recourse. Offered inspection.\n\nAddress: 7 Dickinson St in Inman (not Dickson in Teele). Will visit next week Mon-Wed while team is in Somerville.',
    created_by: 'demo-owner-id',
    created_at: '2026-03-31T10:00:00Z',
    updated_at: '2026-03-31T17:41:00Z',
    assignee: null,
  },
  {
    id: 'job-qargo',
    job_number: 9,
    title: 'Qargo Coffee - Cafe Buildout (Demo, Slab, Flooring, Backsplash)',
    status: 'cancelled',
    customer_id: 'cust-qargo',
    client_name: 'Qargo Coffee',
    client_phone: null,
    client_email: null,
    client_address: '99 Blackstone St, Boston, MA 02109',
    job_type: 'Floor Tile',
    square_footage: null,
    scope_notes: 'Commercial cafe buildout — Demo (drywall, studs, slab cuts), Concrete slab patching, SPC flooring, Ceramic tile (BOH), Backsplash.\n\nCustomer supplies SPC flooring, ceramic tile, backsplash tile. We provide all labor, tools, thinset, grout, leveling.',
    scheduled_start: null,
    scheduled_end: null,
    estimated_days: null,
    actual_days: null,
    estimated_cost: null,
    actual_cost: null,
    amount_invoiced: 0,
    amount_paid: 0,
    line_items: [],
    stripe_customer_id: null,
    notion_page_id: '31135a99-cefd-81ba-9b65-ec2dbf22b043',
    notion_last_synced_at: '2026-04-03T14:00:00Z',
    assigned_to: null,
    notes: 'Site visit recommended before quoting. Client requests: line-item breakdown, schedule, inclusions/exclusions, licenses/insurance, payment terms.',
    created_by: 'demo-owner-id',
    created_at: '2026-02-23T10:00:00Z',
    updated_at: '2026-04-02T17:14:00Z',
    assignee: null,
  },
]

// Invoices based on real job data
export const demoInvoices: Invoice[] = [
  {
    id: 'inv-brooks-1',
    job_id: 'job-brooks',
    customer_id: 'cust-brooks',
    invoice_number: 'INV-2026-001',
    amount: 1623,
    status: 'paid',
    due_date: '2026-02-15',
    stripe_invoice_id: null,
    line_items: [
      { description: 'Strata Mat (prorated) + Thinset + Sealer', quantity: 1, unit_price: 237.50, amount: 237.50, type: 'product', unit: 'lot' },
      { description: 'Hexagon tile installation + sealer (55 sq ft)', quantity: 1, unit_price: 1385.50, amount: 1385.50, type: 'service', unit: 'job' },
    ],
    created_at: '2026-01-30T17:00:00Z',
    updated_at: '2026-02-10T09:00:00Z',
  },
  {
    id: 'inv-wickersty-demo',
    job_id: 'job-wickersty',
    customer_id: 'cust-wickersty',
    invoice_number: 'INV-2026-002',
    amount: 400,
    status: 'sent',
    due_date: '2026-04-10',
    stripe_invoice_id: null,
    line_items: [
      { description: 'Partial tile demo', quantity: 1, unit_price: 250, amount: 250, type: 'service', unit: 'job' },
      { description: 'Trash disposal', quantity: 1, unit_price: 150, amount: 150, type: 'service', unit: 'job' },
    ],
    created_at: '2026-03-25T10:00:00Z',
    updated_at: '2026-03-25T10:00:00Z',
  },
  {
    id: 'inv-wickersty-install',
    job_id: 'job-wickersty',
    customer_id: 'cust-wickersty',
    invoice_number: 'INV-2026-003',
    amount: 3500,
    status: 'sent',
    due_date: '2026-04-15',
    stripe_invoice_id: null,
    line_items: [
      { description: 'Floor tile installation (280 sq ft @ $12.50/sq ft)', quantity: 280, unit_price: 12.50, amount: 3500, type: 'service', unit: 'sq ft' },
    ],
    created_at: '2026-03-25T10:30:00Z',
    updated_at: '2026-03-25T10:30:00Z',
  },
]

export const demoCustomersWithStats: CustomerWithStats[] = demoCustomers.map((c) => {
  const customerJobs = demoJobs.filter((j) => j.customer_id === c.id)
  const paidInvoices = demoInvoices.filter((inv) => inv.customer_id === c.id && inv.status === 'paid')
  const totalRevenue = paidInvoices.reduce((sum, inv) => sum + inv.amount, 0)
  const lastJob = customerJobs.sort((a, b) => b.created_at.localeCompare(a.created_at))[0]
  return {
    ...c,
    job_count: customerJobs.length,
    total_revenue: totalRevenue,
    last_job_date: lastJob?.created_at ?? null,
  }
})

export function getDemoJob(id: string): JobWithAssignee | undefined {
  return demoJobs.find((j) => j.id === id)
}

export function getDemoInvoicesForJob(jobId: string): Invoice[] {
  return demoInvoices.filter((inv) => inv.job_id === jobId)
}

export function getDemoInvoice(id: string): InvoiceWithJob | undefined {
  const invoice = demoInvoices.find((inv) => inv.id === id)
  if (!invoice) return undefined
  const job = demoJobs.find((j) => j.id === invoice.job_id) ?? null
  return { ...invoice, job }
}

export function getAllDemoInvoices(): InvoiceWithJob[] {
  return demoInvoices.map((inv) => ({
    ...inv,
    job: demoJobs.find((j) => j.id === inv.job_id) ?? null,
  }))
}
